-- MySQL Script generated by MySQL Workbench
-- 07/08/16 10:32:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema st
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema st
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `st` DEFAULT CHARACTER SET utf8 ;
USE `st` ;

-- -----------------------------------------------------
-- Table `st`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Cliente` (
  `Codigo_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Movil` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Talla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Talla` (
  `Codigo_Talla` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(45) NOT NULL,
  `Letra` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Talla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Color` (
  `Codigo_Color` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Estilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Estilo` (
  `Codigo_Estilo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_Estilo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Tela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Tela` (
  `Codigo_Tela` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Tela`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Estampado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Estampado` (
  `Codigo_Estampado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Estampado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Producto` (
  `Codigo_Producto` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Tela` INT NOT NULL,
  `Codigo_Estilo` INT NOT NULL,
  `Codigo_Talla` INT NOT NULL,
  `Codigo_Color` INT NOT NULL,
  `Codigo_Estampado` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Stock` DECIMAL NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Producto`),
  INDEX `fk_Producto_Talla1_idx` (`Codigo_Talla` ASC),
  INDEX `fk_Producto_Color1_idx` (`Codigo_Color` ASC),
  INDEX `fk_Producto_Estilo1_idx` (`Codigo_Estilo` ASC),
  INDEX `fk_Producto_Tipo_Tela1_idx` (`Codigo_Tela` ASC),
  INDEX `fk_Producto_Estampado1_idx` (`Codigo_Estampado` ASC),
  CONSTRAINT `fk_Producto_Talla1`
    FOREIGN KEY (`Codigo_Talla`)
    REFERENCES `st`.`Talla` (`Codigo_Talla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Color1`
    FOREIGN KEY (`Codigo_Color`)
    REFERENCES `st`.`Color` (`Codigo_Color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Estilo1`
    FOREIGN KEY (`Codigo_Estilo`)
    REFERENCES `st`.`Estilo` (`Codigo_Estilo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Tipo_Tela1`
    FOREIGN KEY (`Codigo_Tela`)
    REFERENCES `st`.`Tela` (`Codigo_Tela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Estampado1`
    FOREIGN KEY (`Codigo_Estampado`)
    REFERENCES `st`.`Estampado` (`Codigo_Estampado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Venta` (
  `Codigo_Venta` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Cliente` INT NOT NULL,
  `Vendedor` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`Codigo_Venta`),
  INDEX `fk_Factura_Cliente1_idx` (`Codigo_Cliente` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Codigo_Cliente`)
    REFERENCES `st`.`Cliente` (`Codigo_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Insumo` (
  `Codigo_Insumo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Referencia` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Fecha_Compra` DATE NOT NULL,
  `Fecha_Vencimiento` DATE NOT NULL,
  PRIMARY KEY (`Codigo_Insumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`Compra` (
  `Codigo_Compra` INT NOT NULL AUTO_INCREMENT,
  `Comprador` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`Codigo_Compra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`DetalleVenta` (
  `Codigo_Detalle_Venta` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Venta` INT NOT NULL,
  `Codigo_Producto` INT NOT NULL,
  `Cantidad` DECIMAL NOT NULL,
  `Precio` DOUBLE NULL,
  PRIMARY KEY (`Codigo_Detalle_Venta`, `Codigo_Venta`),
  INDEX `fk_MovimientoProducto_Producto1_idx` (`Codigo_Producto` ASC),
  INDEX `fk_Venta_Factura1_idx` (`Codigo_Venta` ASC),
  CONSTRAINT `fk_MovimientoProducto_Producto1`
    FOREIGN KEY (`Codigo_Producto`)
    REFERENCES `st`.`Producto` (`Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Factura1`
    FOREIGN KEY (`Codigo_Venta`)
    REFERENCES `st`.`Venta` (`Codigo_Venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`DetalleInsumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`DetalleInsumo` (
  `Codigo_Detalle_Insumo` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Producto` INT NOT NULL,
  `Codigo_Insumo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  INDEX `fk_Detalle_Insumo1_idx` (`Codigo_Insumo` ASC),
  INDEX `fk_Detalle_Producto1_idx` (`Codigo_Producto` ASC),
  PRIMARY KEY (`Codigo_Detalle_Insumo`, `Codigo_Producto`),
  CONSTRAINT `fk_Detalle_Insumo1`
    FOREIGN KEY (`Codigo_Insumo`)
    REFERENCES `st`.`Insumo` (`Codigo_Insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Producto1`
    FOREIGN KEY (`Codigo_Producto`)
    REFERENCES `st`.`Producto` (`Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `st`.`DetalleCompra` (
  `Codigo_Detalle_Compra` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Compra` INT NOT NULL,
  `Codigo_Insumo` INT NOT NULL,
  `Cantidad` DECIMAL NOT NULL,
  `Precio` DOUBLE NULL,
  INDEX `fk_Detalle_Insumo1_idx` (`Codigo_Insumo` ASC),
  PRIMARY KEY (`Codigo_Detalle_Compra`, `Codigo_Compra`),
  INDEX `fk_DetalleCompra_Compra1_idx` (`Codigo_Compra` ASC),
  CONSTRAINT `fk_Detalle_Insumo10`
    FOREIGN KEY (`Codigo_Insumo`)
    REFERENCES `st`.`Insumo` (`Codigo_Insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleCompra_Compra1`
    FOREIGN KEY (`Codigo_Compra`)
    REFERENCES `st`.`Compra` (`Codigo_Compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
