# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.AutoField(db_column='Codigo_Cliente', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('cedula', models.CharField(db_column='Cedula', max_length=45)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_Nacimiento')),
                ('telefono', models.CharField(db_column='Telefono', max_length=45)),
                ('direccion', models.CharField(db_column='Direccion', max_length=45)),
                ('movil', models.CharField(blank=True, db_column='Movil', max_length=45, null=True)),
                ('email', models.CharField(db_column='Email', max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'cliente',
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('codigo_color', models.AutoField(db_column='Codigo_Color', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('referencia', models.CharField(blank=True, db_column='Referencia', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'color',
                'verbose_name_plural': 'Colores',
                'verbose_name': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigo_compra', models.AutoField(db_column='Codigo_Compra', primary_key=True, serialize=False)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=45)),
                ('precio', models.FloatField(db_column='Precio')),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'managed': False,
                'db_table': 'compra',
                'verbose_name_plural': 'Compras',
                'verbose_name': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('codigo_detalle', models.AutoField(db_column='Codigo_Detalle', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45)),
                ('referencia', models.CharField(db_column='Referencia', max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'detalle',
                'verbose_name_plural': 'Detalles',
                'verbose_name': 'Detalle',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo_empleado', models.AutoField(db_column='Codigo_Empleado', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='Cedula', max_length=45)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_Nacimiento')),
                ('fecha_contratacion', models.DateField(db_column='Fecha_Contratacion')),
                ('telefono', models.CharField(db_column='Telefono', max_length=45)),
                ('direccion', models.CharField(db_column='Direccion', max_length=45)),
                ('movil', models.CharField(blank=True, db_column='Movil', max_length=45, null=True)),
                ('email', models.CharField(db_column='Email', max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'empleado',
                'verbose_name_plural': 'Empleados',
                'verbose_name': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('codigo_estampado', models.AutoField(db_column='Codigo_Estampado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('imagen', models.CharField(blank=True, db_column='Imagen', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'estampado',
                'verbose_name_plural': 'Estampados',
                'verbose_name': 'Estampado',
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('codigo_estilo', models.AutoField(db_column='Codigo_Estilo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'estilo',
                'verbose_name_plural': 'Estilos',
                'verbose_name': 'Estilo',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.AutoField(db_column='Codigo_Factura', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('total', models.FloatField(db_column='Total')),
            ],
            options={
                'managed': False,
                'db_table': 'factura',
                'verbose_name_plural': 'Facturas',
                'verbose_name': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('codigo_insumo', models.AutoField(db_column='Codigo_Insumo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('referencia', models.CharField(db_column='Referencia', max_length=45)),
                ('tipo', models.CharField(db_column='Tipo', max_length=45)),
                ('fecha_compra', models.DateField(db_column='Fecha_Compra')),
                ('fecha_vencimiento', models.DateField(db_column='Fecha_Vencimiento')),
            ],
            options={
                'managed': False,
                'db_table': 'insumo',
                'verbose_name_plural': 'Insumos',
                'verbose_name': 'Insumo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.AutoField(db_column='Codigo_Producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('precio', models.IntegerField(db_column='Precio')),
                ('stock', models.IntegerField(db_column='Stock')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'producto',
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('codigo_talla', models.AutoField(db_column='Codigo_Talla', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='Numero', max_length=45)),
                ('letra', models.CharField(blank=True, db_column='Letra', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'talla',
                'verbose_name_plural': 'Tallas',
                'verbose_name': 'Talla',
            },
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('codigo_tela', models.AutoField(db_column='Codigo_Tela', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tela',
                'verbose_name_plural': 'Telas',
                'verbose_name': 'Tela',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo_venta', models.AutoField(db_column='Codigo_Venta', primary_key=True, serialize=False)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=45)),
                ('precio', models.FloatField(db_column='Precio')),
            ],
            options={
                'managed': False,
                'db_table': 'venta',
                'verbose_name_plural': 'Ventas',
                'verbose_name': 'Venta',
            },
        ),
    ]
