# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprainsumo',
            fields=[
                ('cod_compra_insumo', models.AutoField(db_column='Cod_Compra_Insumo', primary_key=True, serialize=False)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=45)),
                ('valor', models.FloatField(db_column='Valor')),
            ],
            options={
                'verbose_name_plural': 'Compra de Insumos',
                'verbose_name': 'Compra de Insumo',
                'db_table': 'comprainsumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('cod_estampado', models.AutoField(db_column='Cod_Estampado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estampados',
                'verbose_name': 'Estampado',
                'db_table': 'estampado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('cod_tela', models.AutoField(db_column='Cod_Tela', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Telas',
                'verbose_name': 'Tela',
                'db_table': 'tela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('cod_venta', models.AutoField(db_column='Cod_Venta', primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField(db_column='Fecha_Movimiento')),
                ('monto', models.FloatField(db_column='Monto')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'verbose_name': 'Venta',
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventaproducto',
            fields=[
                ('cod_venta_producto', models.AutoField(db_column='Cod_Venta_Producto', primary_key=True, serialize=False)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=45)),
                ('valor', models.FloatField(db_column='Valor')),
            ],
            options={
                'verbose_name_plural': 'Ventas de Productos',
                'verbose_name': 'Venta de Producto',
                'db_table': 'ventaproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('cod_color', models.AutoField(db_column='Cod_Color', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('referencia', models.CharField(blank=True, db_column='Referencia', max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Colores',
                'verbose_name': 'Color',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('cod_estilo', models.AutoField(db_column='Cod_Estilo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Estilos',
                'verbose_name': 'Estilo',
                'db_table': 'estilo',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('cod_insumo', models.AutoField(db_column='Cod_Insumo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('referencia', models.CharField(db_column='Referencia', max_length=45)),
                ('tipo', models.CharField(db_column='Tipo', max_length=45)),
                ('fecha_compra', models.DateField(db_column='Fecha_Compra')),
                ('fecha_vencimiento', models.DateField(db_column='Fecha_Vencimiento')),
            ],
            options={
                'verbose_name_plural': 'Insumos',
                'verbose_name': 'Insumo',
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Insumoproducto',
            fields=[
                ('cod_insumo_producto', models.AutoField(db_column='Cod_Insumo_Producto', primary_key=True, serialize=False)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=45)),
                ('valor', models.FloatField(db_column='Valor')),
                ('cod_insumo', models.ForeignKey(db_column='Cod_Insumo', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Insumo')),
            ],
            options={
                'verbose_name_plural': 'Insumo de Productos',
                'verbose_name': 'Insumo Producto',
                'db_table': 'insumoproducto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('cod_marca', models.AutoField(db_column='Cod_Marca', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'verbose_name': 'Marca',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('cod_perfil', models.AutoField(db_column='Cod_Perfil', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
                'verbose_name': 'Perfil',
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_persona', models.AutoField(db_column='Cod_Persona', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='Cedula', max_length=45)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_Nacimiento')),
                ('telefono', models.CharField(db_column='Telefono', max_length=45)),
                ('direccion', models.CharField(db_column='Direccion', max_length=45)),
                ('movil', models.CharField(blank=True, db_column='Movil', max_length=45, null=True)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('cod_perfil', models.ForeignKey(db_column='Cod_Perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Perfil')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(db_column='Cod_Producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('valor_venta', models.IntegerField(db_column='Valor_Venta')),
                ('valor_produccion', models.IntegerField(db_column='Valor_Produccion')),
                ('cantidad_existente', models.IntegerField(db_column='Cantidad_Existente')),
                ('stock_minimo', models.IntegerField(db_column='Stock_Minimo')),
                ('stock_maximo', models.IntegerField(db_column='Stock_Maximo')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
                ('cod_color', models.ForeignKey(db_column='Cod_Color', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Color')),
                ('cod_estampado', models.ForeignKey(db_column='Cod_Estampado', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Estampado')),
                ('cod_estilo', models.ForeignKey(db_column='Cod_Estilo', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Estilo')),
                ('cod_marca', models.ForeignKey(db_column='Cod_Marca', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Marca')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('cod_talla', models.AutoField(db_column='Cod_Talla', primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=45, null=True)),
                ('letra', models.CharField(blank=True, db_column='Letra', max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tallas',
                'verbose_name': 'Talla',
                'db_table': 'talla',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_talla',
            field=models.ForeignKey(db_column='Cod_Talla', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Talla'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_tela',
            field=models.ForeignKey(db_column='Cod_Tela', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Tela'),
        ),
        migrations.AddField(
            model_name='insumoproducto',
            name='cod_producto',
            field=models.ForeignKey(db_column='Cod_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='Stamping.Producto'),
        ),
    ]
